import * as React from 'react'
const LoadingIcon = (props) => (
    <svg
        xmlns="http://www.w3.org/2000/svg"
        width={100}
        height={100}
        preserveAspectRatio="xMidYMid"
        style={{
            margin: 'auto',
            background: '0 0',
            display: 'block',
        }}
        viewBox="0 0 100 100"
        {...props}
    >
        <rect
            width={5}
            height={15}
            x={47.5}
            y={12.5}
            fill="#e1e1e1"
            rx={1.5}
            ry={1.5}
        >
            <animate
                attributeName="opacity"
                begin="-0.9333333333333333s"
                dur="1s"
                keyTimes="0;1"
                repeatCount="indefinite"
                values="1;0"
            />
        </rect>
        <rect
            width={5}
            height={15}
            x={47.5}
            y={12.5}
            fill="#e1e1e1"
            rx={1.5}
            ry={1.5}
            transform="rotate(24 50 50)"
        >
            <animate
                attributeName="opacity"
                begin="-0.8666666666666667s"
                dur="1s"
                keyTimes="0;1"
                repeatCount="indefinite"
                values="1;0"
            />
        </rect>
        <rect
            width={5}
            height={15}
            x={47.5}
            y={12.5}
            fill="#e1e1e1"
            rx={1.5}
            ry={1.5}
            transform="rotate(48 50 50)"
        >
            <animate
                attributeName="opacity"
                begin="-0.8s"
                dur="1s"
                keyTimes="0;1"
                repeatCount="indefinite"
                values="1;0"
            />
        </rect>
        <rect
            width={5}
            height={15}
            x={47.5}
            y={12.5}
            fill="#e1e1e1"
            rx={1.5}
            ry={1.5}
            transform="rotate(72 50 50)"
        >
            <animate
                attributeName="opacity"
                begin="-0.7333333333333333s"
                dur="1s"
                keyTimes="0;1"
                repeatCount="indefinite"
                values="1;0"
            />
        </rect>
        <rect
            width={5}
            height={15}
            x={47.5}
            y={12.5}
            fill="#e1e1e1"
            rx={1.5}
            ry={1.5}
            transform="rotate(96 50 50)"
        >
            <animate
                attributeName="opacity"
                begin="-0.6666666666666666s"
                dur="1s"
                keyTimes="0;1"
                repeatCount="indefinite"
                values="1;0"
            />
        </rect>
        <rect
            width={5}
            height={15}
            x={47.5}
            y={12.5}
            fill="#e1e1e1"
            rx={1.5}
            ry={1.5}
            transform="rotate(120 50 50)"
        >
            <animate
                attributeName="opacity"
                begin="-0.6s"
                dur="1s"
                keyTimes="0;1"
                repeatCount="indefinite"
                values="1;0"
            />
        </rect>
        <rect
            width={5}
            height={15}
            x={47.5}
            y={12.5}
            fill="#e1e1e1"
            rx={1.5}
            ry={1.5}
            transform="rotate(144 50 50)"
        >
            <animate
                attributeName="opacity"
                begin="-0.5333333333333333s"
                dur="1s"
                keyTimes="0;1"
                repeatCount="indefinite"
                values="1;0"
            />
        </rect>
        <rect
            width={5}
            height={15}
            x={47.5}
            y={12.5}
            fill="#e1e1e1"
            rx={1.5}
            ry={1.5}
            transform="rotate(168 50 50)"
        >
            <animate
                attributeName="opacity"
                begin="-0.4666666666666667s"
                dur="1s"
                keyTimes="0;1"
                repeatCount="indefinite"
                values="1;0"
            />
        </rect>
        <rect
            width={5}
            height={15}
            x={47.5}
            y={12.5}
            fill="#e1e1e1"
            rx={1.5}
            ry={1.5}
            transform="rotate(192 50 50)"
        >
            <animate
                attributeName="opacity"
                begin="-0.4s"
                dur="1s"
                keyTimes="0;1"
                repeatCount="indefinite"
                values="1;0"
            />
        </rect>
        <rect
            width={5}
            height={15}
            x={47.5}
            y={12.5}
            fill="#e1e1e1"
            rx={1.5}
            ry={1.5}
            transform="rotate(216 50 50)"
        >
            <animate
                attributeName="opacity"
                begin="-0.3333333333333333s"
                dur="1s"
                keyTimes="0;1"
                repeatCount="indefinite"
                values="1;0"
            />
        </rect>
        <rect
            width={5}
            height={15}
            x={47.5}
            y={12.5}
            fill="#e1e1e1"
            rx={1.5}
            ry={1.5}
            transform="rotate(240 50 50)"
        >
            <animate
                attributeName="opacity"
                begin="-0.26666666666666666s"
                dur="1s"
                keyTimes="0;1"
                repeatCount="indefinite"
                values="1;0"
            />
        </rect>
        <rect
            width={5}
            height={15}
            x={47.5}
            y={12.5}
            fill="#e1e1e1"
            rx={1.5}
            ry={1.5}
            transform="rotate(264 50 50)"
        >
            <animate
                attributeName="opacity"
                begin="-0.2s"
                dur="1s"
                keyTimes="0;1"
                repeatCount="indefinite"
                values="1;0"
            />
        </rect>
        <rect
            width={5}
            height={15}
            x={47.5}
            y={12.5}
            fill="#e1e1e1"
            rx={1.5}
            ry={1.5}
            transform="rotate(288 50 50)"
        >
            <animate
                attributeName="opacity"
                begin="-0.13333333333333333s"
                dur="1s"
                keyTimes="0;1"
                repeatCount="indefinite"
                values="1;0"
            />
        </rect>
        <rect
            width={5}
            height={15}
            x={47.5}
            y={12.5}
            fill="#e1e1e1"
            rx={1.5}
            ry={1.5}
            transform="rotate(312 50 50)"
        >
            <animate
                attributeName="opacity"
                begin="-0.06666666666666667s"
                dur="1s"
                keyTimes="0;1"
                repeatCount="indefinite"
                values="1;0"
            />
        </rect>
        <rect
            width={5}
            height={15}
            x={47.5}
            y={12.5}
            fill="#e1e1e1"
            rx={1.5}
            ry={1.5}
            transform="rotate(336 50 50)"
        >
            <animate
                attributeName="opacity"
                begin="0s"
                dur="1s"
                keyTimes="0;1"
                repeatCount="indefinite"
                values="1;0"
            />
        </rect>
    </svg>
)
export default LoadingIcon
